### ISSUE TITLE
[priority: HIGH] add a contributors.json file will all data

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#107]
We need to store our contributors details in a json file.

```js
{
  "profiles": [
    {
      "name": "DevvSakib",
      "avatarUrl": "https://avatars.githubusercontent.com/u/88339569?v=4",
      "github": "devvsakib",
      "twitter": "devvsakib"
    }
 ]
}
```

if they don't have twitter, you can skip - "twitter": " "

**Comment by udaykahar** [comment]
hey @devvsakib please assign this to me

**Comment by devvsakib** [comment]
> hey @devvsakib please assign this to me

suree

**Comment by PriteshKiri** [comment]
Hey, can you assign this to me

**Comment by devvsakib** [comment]
> Hey, can you assign this to me

already assigned someone, you can try other issue

**Comment by devvsakib** [comment]
file added thanks.
