### ISSUE TITLE
[FIX] fix mobile navbar

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#11]
currently mobile navbar are broken. please it responsive.

**Comment by abel-otegbola** [comment]
Hi @devvsakib can you assign this to me?

**Comment by devvsakib** [comment]
> Hi @devvsakib can you assign this to me?

assigned you

**Comment by abel-otegbola** [comment]
Thanks. I'll work on it as soon as possible.

**Comment by devvsakib** [comment]
> I want to clarify something. You want to me to fix the navbar for the clone-tesla project.?

projects folder only for if you have any project, you can add here. there are a index file , and it has a navbar.

**Comment by abel-otegbola** [comment]
Alright.

**Comment by bhoopesh369** [comment]
Can i work on this issue?

**Comment by devvsakib** [comment]
> Can i work on this issue? @devvsakib

go for it, assigned

**Comment by devvsakib** [comment]
> Can i work on this issue? @devvsakib

and you can add a hamburger menu,
