### ISSUE TITLE
[BRANCH - "convert-react"] website reloading while navigating page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#114]
## Navigate to the folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to the convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Feature?
NO

## Bug?
Website reloading while we navigate the menu, it shouldn't. check if you are able to solve this bug.

Task:
clone this repo, checkout to convert-react branch, and work on the navbar!

### Expected behavior:
 website shouldn't reload while navigating from one page to another page. But Logo working fine.

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
Assign this to me @devvsakib

**Comment by yes-im-harsh** [comment]
@devvsakib Check PR: #116

**Comment by devvsakib** [comment]
#116  it didn't solve

**Comment by devvsakib** [comment]
solved commit #3f6b285
