### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#123]
## Feature?
Update the readme file with these screenshots
![image](https://user-images.githubusercontent.com/88339569/198034080-5d66a904-bcfc-41ba-a64e-098ecc1e6dc4.png)

![image](https://user-images.githubusercontent.com/88339569/198034159-84c27f7c-14ac-49e8-aaf7-8d01fcee8db7.png)

## Bug?
No

Task:
add those screenshots in assets folder.
Just delete this screenshot
![image](https://user-images.githubusercontent.com/88339569/198034415-f18667a5-7c7e-480a-acaa-7c3999f5fdd4.png)
and add those 2 screenshots here

and delete this line, add "PowerTheWeb is an open-source project to help web developers make their road easy to become a successful web developer"
![image](https://user-images.githubusercontent.com/88339569/198034825-e24bbded-08bb-4def-a8db-183e6f9d05d8.png)

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by thomasjvu** [comment]
Hi there! I'd like to work on this issue.

**Comment by devvsakib** [comment]
> Hi there! I'd like to work on this issue.

assigned

**Comment by devvsakib** [comment]
solved by #124
