### ISSUE TITLE
[BRANCH - "convert-react"] add a bottom to top scroll button

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#135]
## Navigate to the folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to the convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Feature?
Add a Bottom to Top scroll button
it's hard to scroll when you are on mobile device, so please add a Bottom to Top button  with an arrow icon

## Bug?
NO

Task:
add button here
Desktop version position:
![image](https://user-images.githubusercontent.com/88339569/198207936-948e05a0-b268-416b-af23-c982595d7f7d.png)
Mobile version position:
![image](https://user-images.githubusercontent.com/88339569/198208424-12394870-fdd7-493e-ba1f-66819ce1c751.png)

please make sure, it only shows if you scroll down. otherwise, it won't show.

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
Assign this to me @devvsakib

**Comment by devvsakib** [comment]
> Assign this to me @devvsakib

assigned

**Comment by yes-im-harsh** [comment]
Should I have to Implement It on all the pages or only on contributors page @devvsakib

**Comment by devvsakib** [comment]
> Should I have to Implement It on all the pages or only on contributors page @devvsakib 

all page, or try to use in app.js file

**Comment by yes-im-harsh** [comment]
@devvsakib  Check PR: #137

**Comment by devvsakib** [comment]
Solved by #134

**Comment by devvsakib** [comment]
Solved by #137
