### ISSUE TITLE
[BRANCH - "convert-react"] hide scrollbar on every brwoser

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#136]
## Navigate to the folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to the convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Feature?
Hide the scrollbar, it looks disgusting. do not use overflow hidden, 
![image](https://user-images.githubusercontent.com/88339569/198209264-ffedbba0-a3c1-45e5-91f7-a97cd84555fe.png)

## Bug?
Describe here

Task:
hide scrollbar for the body.
write CSS in main.css file to apply to the entire website
body::-webkit-scrollbar{
    display: none
}
this CSS for chrome, write for IE, Edge and Firefox  too

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
I am on it @devvsakib

**Comment by devvsakib** [comment]
> I am on it @devvsakib

assigned

**Comment by yes-im-harsh** [comment]
@devvsakib Check PR #137

**Comment by devvsakib** [comment]
Solved by #137
