### ISSUE TITLE
add a ROADMAP page 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#139]
add a roadmap page and link to the navbar.
add some frontend guideline

**Comment by zaahmed-nisum-com** [comment]
@devvsakib  can i work on it, please? assign it to me

**Comment by devvsakib** [comment]
> @devvsakib can i work on it, please? assign it to me

hi @zaahmed-nisum-com  page added, you can add frontend suggestions for beginners, would you love to do that?

**Comment by zainbinfurqan** [comment]
is it open!?

**Comment by devvsakib** [comment]
> is it open!?

 check #40
