### ISSUE TITLE
[FEATURE] add a BLOG page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#22]
We need a blog page in our website. With Blog page, we can showcase our **contributors** post/blog.

### Details
- creat blog page
- add nav
- add demo blog card (design as you wish)

Please comment if you want to assign here.

**Comment by burhanharoon** [comment]
Assign this to me. I would love to work on this!

**Comment by devvsakib** [comment]
> Assign this to me. I would love to work on this!

assigned

**Comment by devvsakib** [comment]
SOLVED BY #25
