### ISSUE TITLE
[MAJOR] convert website into REACT website

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#23]
## Major Update
So far we did well. Now its time to convert our **website** into **react** website.

Now we are using simple html css static website. But we are going to convert this into react.

Please comment only if you have exprience

**Comment by Amank-root** [comment]
Hi, @devvsakib your static website is not at all function, Navbar element without function, etc

**Comment by devvsakib** [comment]
> Hi, @devvsakib your static website is not at all function, Navbar element without function, etc 
> 

yes, thats why we are going to convert this website into dynamic website using reactjs

**Comment by piyush-mahajan** [comment]
hey, can you assign me this task?

**Comment by devvsakib** [comment]
> hey, can you assign me this task?

yeah sure
