### ISSUE TITLE
[FEATURE] add a contributor page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#37]
We need to add our contributor page, where we can showcase our all contributor.

Please 
1. create a contributor.html 
2. add nav
3. link to index.html

assign to get Hacktoberfest label

**Comment by danieleavolio** [comment]
Can I have this?

**Comment by abhi87374** [comment]
please assign this to me...

**Comment by devvsakib** [comment]
> please assign this to me...

assigned
