### ISSUE TITLE
[FEATURE] add  CONTRIBUTOR page 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#4]
add a simple contributor page.
design concept:
- circle image,
- full name,
- Twitter, GitHub link icon.

3/4 profile in a row

**Comment by ProtyayMnd50** [comment]
could you assign it to me @devvsakib pls?

**Comment by devvsakib** [comment]
> could you assign it to me @devvsakib pls?

assigned you
