### ISSUE TITLE
[IMPROPER] improve index file design

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#44]
So far we all did fantactic, its time to improve our website design. if you have any design idea please let us know, we will assign you and label your pr as Hacktoberfest

**Comment by varunsh17** [comment]
Please specify more , and I wanna work on this issue !

**Comment by devvsakib** [comment]
> Please specify more , and I wanna work on this issue !

add darkmode

**Comment by varunsh17** [comment]
If you are talking about darkmode on the website, then it can be made..
assign the issue, I will start working :)

**Comment by devvsakib** [comment]
@varunsh17  any update?

**Comment by varunsh17** [comment]
Yes,
You can assign it to someone else.. 
Sorry I got a more intresting task

**Comment by devvsakib** [comment]
> Yes, You can assign it to someone else.. Sorry I got a more intresting task

go for your interesting task, good luck😄
