### ISSUE TITLE
[FEATURE] add footer

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#47]
please add a footer,
footer text "PowerTheWeb | Developed By PTW Community @ 2022"

**Comment by Aditya-wani02** [comment]
Like to work,,,

What should I use...
New Here...

**Comment by devvsakib** [comment]
> Like to work,,,
> 
> What should I use... New Here...



> @devvsakib Please assign this issue to me, I would like to work on it.

assigned

**Comment by devvsakib** [comment]
@Aditya-wani02  nothing much, can you work with this issue:  #48  ? cz already someone assigned for this work
