### ISSUE TITLE
[FEATURE] add a FAQ page with accordion

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#48]
we need a FAQ page with accordion.

use random questions and answer, later we will change it
sample:
![image](https://user-images.githubusercontent.com/88339569/196474449-1edfbb3f-cd1c-42d5-9cfa-9b33bb99b442.png)

**Comment by swapn652** [comment]
Hey, can I work on this?

**Comment by devvsakib** [comment]
> Hey, can I work on this?

yeah sure

**Comment by devvsakib** [comment]
> Hey, can I work on this?

assigned

**Comment by devvsakib** [comment]
@swapn652  any update?

**Comment by swapn652** [comment]
@devvsakib sorry, I was busy with some other work. Will do it within an hour

**Comment by devvsakib** [comment]
@vickywane do you want

**Comment by vickywane** [comment]
Sure
