### ISSUE TITLE
Site not working properly

### ISSUE THREAD

**Issue by swapn652** [devvsakib/hacktoberfest-react-project#49]
## Contributors' tab
![image](https://user-images.githubusercontent.com/70851202/196478700-1c6fb0a2-d647-463b-b3f3-a699b3a8f533.png)

## Projects' tab
![image](https://user-images.githubusercontent.com/70851202/196478790-8d729512-e49a-4217-951d-e65198266073.png)

**Comment by devvsakib** [comment]
> ## Contributors' tab
> 
> ![image](https://user-images.githubusercontent.com/70851202/196478700-1c6fb0a2-d647-463b-b3f3-a699b3a8f533.png)
> ## Projects' tab
> 
> ![image](https://user-images.githubusercontent.com/70851202/196478790-8d729512-e49a-4217-951d-e65198266073.png)

thats an issue, thank you for check, you can work on it

**Comment by swapn652** [comment]
@devvsakib fine assign me. I will work on it.

**Comment by devvsakib** [comment]
> @devvsakib fine assign me. I will work on it.

assigned
