### ISSUE TITLE
fetch contributors profile from json file to contributors page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#60]
So far we have our contributors json file, its time to fetch them to our contributors.html file.
Please comment if you have better knowledge about fetch or map functions

Todo:
create a script.js file,
fetch all json data to contributors page

make pr, hacktoberfest label will be added

**Comment by devvsakib** [comment]
better if you watch this issue first #61

**Comment by devvsakib** [comment]
@vickywane this issue for you

**Comment by nitoC** [comment]
can I be assigned this?

**Comment by devvsakib** [comment]
> can I be assigned this?

ok

**Comment by devvsakib** [comment]
solved by #84
