### ISSUE TITLE
create contributors profile card

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#61]
please create contributors profile card on contributors.html file

sample design:
![image](https://user-images.githubusercontent.com/88339569/197172571-b2ce8f4f-64cc-4cb3-a3b4-3f18c8623fa0.png)

add title "CONTRIBUTORS"

**Comment by devvsakib** [comment]
after you create card, you can go for this issue #60

**Comment by vickywane** [comment]
I am available to take this up @devvsakib

**Comment by udaykahar** [comment]
Hi @jsvigneshkanna , I can work on this, can you please assign me?

**Comment by udaykahar** [comment]
Hi @devvsakib , I can work on this, can you please assign me?

**Comment by devvsakib** [comment]
> Hi @devvsakib , I can work on this, can you please assign me?

sure, assigned

**Comment by devvsakib** [comment]
> I am available to take this up @devvsakib

assigned

**Comment by udaykahar** [comment]
ready here! :)

**Comment by devvsakib** [comment]
> ready here! :)

i dont see your pr, please make pr

**Comment by udaykahar** [comment]
i meant I'm ready to work!! it's under development now

**Comment by devvsakib** [comment]
> i meant I'm ready to work!! it's under development now

ouu that's great.

**Comment by devvsakib** [comment]
> i meant I'm ready to work!! it's under development now

and add your details in this file Contributors.json

**Comment by vickywane** [comment]
@udaykahar how do you suggest we collaborate on this?

I have the work done locally.

**Comment by udaykahar** [comment]
@vickywane I have designed cards

**Comment by vickywane** [comment]
@udaykahar Nice. 

I have done the initial data setup for the page. I will complete the styling within the next hours. 
I have opened a PR for this [here](https://github.com/devvsakib/hacktoberfest-react-project/pull/65).

I'll finish it up soon. 

Cc: @devvsakib

**Comment by devvsakib** [comment]
> @udaykahar Nice.
> 
> I have done the initial data setup for the page. I will complete the styling within the next hours. I have opened a PR for this [here](https://github.com/devvsakib/hacktoberfest-react-project/pull/65).
> 
> I'll finish it up soon.
> 
> Cc: @devvsakib

okk, then I will check again. then you can check new issues, new issues has lots of work, we can do something better together

**Comment by vickywane** [comment]
@devvsakib i wanted to finish it up before you merged the PR. 

You could have left it open for a day for me to finish up. 

Should I open another when done?

**Comment by devvsakib** [comment]
> @devvsakib i wanted to finish it up before you merged the PR.
> 
> You could have left it open for a day for me to finish up.
> 
> Should I open another when done?

no, I marged for now, cz our page was empty, when you done, make commit and push

**Comment by udaykahar** [comment]
why it is repopend?

**Comment by devvsakib** [comment]
> why it is re-opened?

thanks for checking, it was mistake
