### ISSUE TITLE
[branch-CONVERT-REACT] create footer components for main website

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#75]
Check 2nd Branch, name- convert-react
Clone this, navigate to main-website folder,this is our main website we are converting into react website,

Task:
Just create a simple footer like that - 
![image](https://user-images.githubusercontent.com/88339569/197269199-7e81f643-ca98-4a1f-90c2-66874eb5ae99.png)

You can join our discord server - lets build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
I am on it.

**Comment by yes-im-harsh** [comment]
@devvsakib  check PR: #77

**Comment by yes-im-harsh** [comment]
Take a look @devvsakib PR: #81

**Comment by devvsakib** [comment]
solved #81
