### ISSUE TITLE
contributors card not inline

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#76]
please solve this problem, card should be inline.

use flex in ul tag to resolve

![image](https://user-images.githubusercontent.com/88339569/197270778-4dfea9d3-747c-4df2-a237-601fa4c89347.png)

**Comment by vickywane** [comment]
Taking this.

**Comment by Sathasivamthirumoorthi** [comment]
Please assign this to me , i would like to work , thanks in advance

**Comment by bhoopesh369** [comment]
can  i work on this @devvsakib

**Comment by devvsakib** [comment]
> Please assign this to me , i would like to work , thanks in advance



> Please assign this to me , i would like to work , thanks in advance

assigned

**Comment by Sathasivamthirumoorthi** [comment]
Is this issue already completed ?

**Comment by devvsakib** [comment]
> Is this issue already completed ?

no

**Comment by vickywane** [comment]
Taking a look once more

**Comment by vickywane** [comment]
@devvsakib Submitted a fix [here](https://github.com/devvsakib/hacktoberfest-react-project/pull/84).

**Comment by devvsakib** [comment]
solved by #84
