### ISSUE TITLE
[BRANCH - "convert-react"] navbar not responsive

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#82]
**Navigate to folder**
Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to convet-react branch, not in the main branch. Add your details to contributors.json file.

## Feature?
Mobile navbar not responsive, make its responsive and add hamburger menu icon for mobile device

## Bug?
NO

Task:
Navbar file has everything you need, in 43line delete the "hidden" class to see the hamburger menu icon, 

You can join our discord server - lets build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by vickywane** [comment]
Taking a look 👀

**Comment by devvsakib** [comment]
> Taking a look 👀

found something?😉😉

**Comment by vickywane** [comment]
Yea. 

I’ll submit a PR in the next few hours

**Comment by vickywane** [comment]
I opened a PR to fix it [here](https://github.com/devvsakib/hacktoberfest-react-project/pull/89).

**Comment by devvsakib** [comment]
@vickywane need some change, please pr to our 2nd branch "convert-react" . everything is ok
![Uploading image.png…]()

**Comment by devvsakib** [comment]
@vickywane need some change, please pr to our 2nd branch "convert-react" . everything is ok
![image](https://user-images.githubusercontent.com/88339569/197341582-88638c90-69b3-4950-a202-a19af9e58f8a.png)

**Comment by vickywane** [comment]
I've done that.

**Comment by vickywane** [comment]
When you open the next feature request in an issue, feel free to quote and assign it to me. 

I'll work on it from there.

**Comment by devvsakib** [comment]
thank you,you can join with us for further work https://discord.gg/xwRbDwnbMr
😉

**Comment by devvsakib** [comment]
@vickywane  i mistakenly deleted your comment, really sorry

**Comment by devvsakib** [comment]
solved by #89
