### ISSUE TITLE
[BRANCH - "convert-react"] DELETE PROJECTS FOLDER

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#85]
**Navigate to folder**
Check 2nd Branch, name- convert-react
Clone this, navigate to main-website folder,this is our main website we are converting into react website,

## Feature?
No

## Bug?
No

Task:
Delete PROJECTS folder. we will add projects later, though we have "main" branch with "PROJECTS" folder so we don't need to have it in our "convert-react" branch. Please be aware, and make pr to convert-react branch

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by yes-im-harsh** [comment]
I am on it.

**Comment by devvsakib** [comment]
> I am on it. @devvsakib

assigned

**Comment by devvsakib** [comment]
solved by #88
