### ISSUE TITLE
[BRANCH - "convert-react"] add a ROADMAP page

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest-react-project#98]
## Navigate to the folder
**Check 2nd Branch, name- convert-react
Clone this, and navigate to main-website folder, this is the main website we are converting into react website after you have done, PR to the convert-react branch, not in the "main" branch. Add your details to contributors.json file.**

## Feature?
We need a roadmap page for the guidline.

## Bug?
Describe here

Task:
Create a page named roadmap, and link to nav

You can join our discord server - let's build together [Join](https://discord.gg/xwRbDwnbMr)

**Comment by vickywane** [comment]
I’m taking this…

**Comment by devvsakib** [comment]
> I’m taking this…

assigned

**Comment by vickywane** [comment]
Opened this [PR](https://github.com/devvsakib/hacktoberfest-react-project/pull/100) for it. 

@devvsakib
